"""
Themed demo bubble scripts — 30-50 messages each, Hinglish mobile-chat style.
Used by seed_demo_chat; messages are (speaker_index, text) into USER_POOLS.
"""

# fmt: off

BOOK_WORMS_USERS = [
    "PageTurner", "MidnightReader", "KindleBae", "FictionFan", "SelfHelpSkeptic",
    "LibraryGhost", "SpoilerAlert", "PoetryNerd", "AudiobookGuy", "BookmarkChaos",
]

BOOK_WORMS_MESSAGES = [
    (0, "koi achhi fiction recommend karo yaar, thriller type"),
    (1, "The Silent Patient padhi? twist solid hai"),
    (2, "main toh ab audiobook pe shift ho gaya, commute pe easy"),
    (3, "audiobook se story feel kam hoti hai mujhe 😅"),
    (4, "self help books overrated lagte hain kabhi kabhi"),
    (5, "depends bhai, Atomic Habits ne genuinely help kiya"),
    (6, "spoiler mat dena koi bhi 👀 main half pe hun"),
    (7, "sorry sorry 😂 continue kar"),
    (0, "physical book vs kindle — team kya?"),
    (8, "kindle for travel, physical for home vibe"),
    (9, "mera bookmark har book mein alag page pe hai 💀"),
    (1, "relatable, mere sticky notes ka alag universe hai"),
    (3, "Indian author suggestion? English ya Hindi dono chalega"),
    (5, "Chetan Bhagat phase sabne guzara hai, no judgment 😂"),
    (2, "Amish Tripathi Shiva series fun thi yaad hai"),
    (4, "mujhe poetry collections pasand hain, Gulzar type"),
    (6, "short stories bhi underrated — Ruskin Bond vibes"),
    (7, "library card ab bhi use karta hai koi?"),
    (0, "haan, Sunday ritual hai mera"),
    (9, "library mein AC + silence = productivity boost"),
    (8, "reading before sleep ya morning?"),
    (1, "night owl reader, 11pm to 1am slot"),
    (3, "morning impossible, brain dead rehta hai"),
    (5, "non-fiction streak 12 days chal rahi hai 🔥"),
    (2, "nice, main fiction streak pe hun lol"),
    (4, "book club join kiya kisi ne kabhi?"),
    (6, "college mein try kiya, sab ne last minute skip"),
    (7, "online book clubs better hain ab"),
    (0, "currently reading Project Hail Mary — sci-fi fans?"),
    (8, "Andy Weir fan reporting ✋"),
    (9, "koi horror recommend karo but not too creepy"),
    (1, "Bird Box mat padhna raat ko 😂"),
    (3, "Dune book ya movie pehle?"),
    (5, "book pehle always, movie disappoint karti hai"),
    (2, "Harry Potter re-read kar raha hun, comfort read"),
    (4, "same energy with Narnia for me"),
    (6, "reading speed slow hai toh kya karein?"),
    (7, "enjoy karo, race nahi hai"),
    (0, "book exchange nearby karte hain kya? 📚"),
    (8, "good idea, main 3 books la sakta hun"),
    (9, "Sunday meetup style? chai + books"),
    (1, "I'm in if location central ho"),
]

SOFTWARE_ENGINEERS_USERS = [
    "TechBro", "CodeNinja", "BugHunter", "StackOverflow", "RemoteDev",
    "InterviewPrep", "StartupCoder", "MemeDev", "NightOwlDev", "GitPush",
]

SOFTWARE_ENGINEERS_MESSAGES = [
    (0, "Cursor ya VS Code? serious question"),
    (1, "Abhi toh Cursor hype chal raha hai 😂"),
    (2, "VS Code + copilot still solid for me"),
    (3, "dono use karta hun project ke hisaab se"),
    (4, "remote job scene kaisa hai ab?"),
    (5, "better than 2023 imo, openings aa rahi hain"),
    (6, "DSA grind kab khatam hoga yaar"),
    (7, "never ends bro, accept kar lo"),
    (8, "production bug 2am pe aaya, classic"),
    (9, "git blame dekh ke regret hota hai"),
    (0, "Python vs JS for backend — fight start 😅"),
    (1, "use case pe depend, dono seekho"),
    (2, "startup mein sab kuch JS mein ho jata hai"),
    (3, "tech stack wars bore ho gaye"),
    (4, "system design interview tips koi?"),
    (5, "YouTube ke concepts + mock interviews help kiye"),
    (6, "Leetcode daily karte ho?"),
    (7, "2 easy 1 medium routine, strict nahi"),
    (8, "AI tools coding speed badha rahe hain sach mein"),
    (9, "but understanding khud ki honi chahiye"),
    (0, "internship stipend kitna expect karein?"),
    (1, "city pe depend, 25-40k range common"),
    (2, "unpaid internship scam hai, avoid"),
    (3, "first job mein brand ya learning?"),
    (4, "learning > brand for first 2 years"),
    (5, "FAANG dream ab bhi alive hai?"),
    (6, "alive hai but path harder"),
    (7, "meme: 'it works on my machine' 🖥️"),
    (8, "deploy Friday ko mat karna, rule #1"),
    (9, "learned the hard way 💀"),
    (0, "work life balance tech mein myth hai kya"),
    (1, "company culture pe depend karti hai"),
    (2, "switch karna easy nahi but possible"),
    (3, "side project koi chala raha hai?"),
    (4, "weekend pe todo app bana raha hun, kabhi finish nahi"),
    (5, "same, 50 repos half finished 😂"),
    (6, "open source contribute kiya kisi ne?"),
    (7, "small docs fix se start kiya tha"),
    (8, "coffee vs tea during debug session"),
    (9, "coffee. always coffee."),
    (0, "bootcamp worth it hai ya self learn?"),
    (1, "self learn + projects + network = enough mostly"),
    (2, "thanks yaar, motivation mila"),
]

STARTUP_FOUNDERS_USERS = [
    "Founder1", "CoFounder", "PitchDeck", "GrowthHacker", "BootstrapKing",
    "VCdreamer", "ProductGuy", "SalesGrind", "BurnoutNear", "PivotMaster",
]

STARTUP_FOUNDERS_MESSAGES = [
    (0, "idea validate kaise karte ho pehle?"),
    (1, "customer interviews, 20 minimum"),
    (2, "landing page + waitlist bhi kaam aata hai"),
    (3, "MVP kitne time mein launch kiya tumne?"),
    (4, "3 months, phir bhi late tha 😅"),
    (5, "funding ya bootstrap — current mood?"),
    (6, "bootstrap until traction, then decide"),
    (7, "CAC bahut high aa raha hai help"),
    (8, "organic + community pe focus karo pehle"),
    (9, "pivot kiya kabhi?"),
    (0, "haan, B2C se B2B shift, best decision"),
    (1, "co-founder dhundna itna hard kyun hai"),
    (2, "trust + skill dono chahiye, rare combo"),
    (3, "solo founder gang 🙋"),
    (4, "respect, main burnout se lad raha hun"),
    (5, "take break bhai, product bhi suffer karta hai"),
    (6, "pitch deck slides kitni honi chahiye?"),
    (7, "10-12 max, investors ko time do"),
    (8, "first 10 customers kaise mile?"),
    (9, "manual outreach, no shame"),
    (0, "LinkedIn cold DM work karta hai?"),
    (1, "personalized ho toh haan, copy paste fail"),
    (2, "pricing mein confuse hun, freemium?"),
    (3, "free tier chhota rakho, value clear ho"),
    (4, "competition se dar lagta hai"),
    (5, "focus on niche, sabko mat lo"),
    (6, "legal paperwork kitna important early stage"),
    (7, "basics cover karo, overthink mat"),
    (8, "motivation low days pe kya karte ho"),
    (9, "walk + phone off + 30 min"),
    (0, "yeh bubble helpful hai, alone feel kam hua"),
    (1, "same, founder loneliness real hai"),
    (2, "accountability partner chahiye kya?"),
    (3, "weekly check-in thread start karte hain"),
    (4, "I'm in"),
    (5, "product market fit ka sign kya hai"),
    (6, "users complain but still come back 😂"),
    (7, "best advice you got as founder?"),
    (8, "ship fast, talk to users daily"),
    (9, "noted 📝"),
]

FITNESS_FREAKS_USERS = [
    "GymRat", "ProteinBro", "CardioQueen", "RestDay", "MealPrep",
    "LegDayPain", "YogaStart", "ScaleObsessed", "MorningRun", "CheatMeal",
]

FITNESS_FREAKS_MESSAGES = [
    (0, "aaj leg day tha, stairs pe jaana mushkil hai 💀"),
    (1, "leg day gang feels your pain"),
    (2, "protein intake kitna grams?"),
    (3, "body weight x 1.6 approx follow karta hun"),
    (4, "vegetarian protein sources batao"),
    (5, "paneer, dal, whey, soy — combo"),
    (6, "cardio before ya after weights?"),
    (7, "after, warna strength drop feel hoti hai"),
    (8, "5k run sub 30 min possible?"),
    (9, "consistent training se ho jayega"),
    (0, "rest day pe guilty feel hota hai"),
    (1, "rest bhi training hai, muscles grow then"),
    (2, "meal prep Sunday karte ho?"),
    (3, "3 din ka khana ek saath, life saver"),
    (4, "cheat meal weekly ya monthly"),
    (5, "weekly, warna mental breakdown 😂"),
    (6, "gym 6am vs 8pm crowd?"),
    (7, "6am peaceful, 8pm too crowded"),
    (8, "yoga for flexibility recommend?"),
    (9, "haan, shoulder pain kam hua mera"),
    (0, "scale weight fluctuate karta hai daily, normal?"),
    (1, "water + salt, don't stress"),
    (2, "cutting phase mein energy low"),
    (3, "slight deficit rakho, crash mat karo"),
    (4, "home workout enough without gym?"),
    (5, "beginners ke liye haan, progressive overload chahiye"),
    (6, "running shoes recommendation budget?"),
    (7, "local store mein try karke lo"),
    (8, "gym buddy chahiye motivation ke liye"),
    (9, "is bubble mein hi buddy mil jaye 😄"),
    (0, "kal subah walk pe kaun free?"),
    (1, "7am park, I'm in"),
    (2, "pre workout coffee ya nahi"),
    (3, "black coffee light, stomach ok ho toh"),
    (4, "creatine worth it?"),
    (5, "cheap aur effective, research backed"),
    (6, "stretching skip mat karo guys"),
    (7, "learned after injury 😅"),
    (8, "fitness journey 6 months update thread?"),
    (9, "monthly update rakhte hain yahan"),
]

ANIME_FANS_USERS = [
    "OtakuDesi", "MangaReader", "SubVsDub", "CosplayMaybe", "ShonenFan",
    "SliceOfLife", "WaifuDebater", "Crunchyroll", "AMVeditor", "NewWeeb",
]

ANIME_FANS_MESSAGES = [
    (0, "new season recommendations do yaar"),
    (1, "Frieren agar nahi dekhi toh start karo"),
    (2, "sub ya dub? eternal debate"),
    (3, "sub always, emotions better lagte hain"),
    (4, "manga padhte ho ya sirf anime?"),
    (5, "donon, manga ahead rehta hai"),
    (6, "One Piece length se darr lagta hai"),
    (7, "worth it, pacing ab better hai"),
    (8, "best starter anime for friends?"),
    (9, "Spy x Family easy entry hai"),
    (0, "character debate: Gojo overrated? 👀"),
    (1, "bold take, fight in replies 😂"),
    (2, "cosplay try kiya kisi ne?"),
    (3, "college fest pe attempt, confidence > accuracy"),
    (4, "AMV banane ka time nahi milta ab"),
    (5, "same, office life cruel hai"),
    (6, "romance anime rec chahiye light wala"),
    (7, "Horimiya sweet hai"),
    (8, "villain arc enjoy karte ho?"),
    (9, "anti hero stories >>>"),
    (0, "merch itna expensive kyun hai"),
    (1, "import duty bhai, pain"),
    (2, "watch party nearby kar sakte hain?"),
    (3, "weekend episode binge plan?"),
    (4, "I'm down, snacks bring karna"),
    (5, "sports anime fans? Haikyuu still goat"),
    (6, "Blue Lock football wale dekho"),
    (7, "Studio Ghibli rewatch kabhi bhi"),
    (8, "sad anime cry session mat do group mein"),
    (9, "Your Name was enough tears for year"),
    (0, "new weeb hu, kahan se start karun"),
    (1, "welcome! no gatekeeping here"),
    (2, "My Hero Academia classic entry"),
    (3, "attack on titan mat late karna spoilers everywhere"),
    (4, "favourite opening theme?"),
    (5, "unravel from Tokyo Ghoul 🔥"),
    (6, "meme templates anime se hi aate hain"),
    (7, "daily life mein references koi samjhe nahi 😭"),
]

CRICKET_LOVERS_USERS = [
    "IPLfan", "TestMatch", "FantasyXI", "KohliFan", "RohitFan",
    "PaceVsSpin", "GullyCricket", "UmpireHate", "StatsNerd", "MatchDay",
]

CRICKET_LOVERS_MESSAGES = [
    (0, "IPL season mein sleep schedule khatam 😂"),
    (1, "same, 7:30 match = dinner on couch"),
    (2, "playing XI prediction aaj ki?"),
    (3, "spin on slow track, pace ko rest"),
    (4, "fantasy team mein captain kaun"),
    (5, "risk liya, all rounder captain"),
    (6, "Test cricket still best format fight me"),
    (7, "5 days commitment tough but pure cricket"),
    (8, "gully cricket rules: one tip one hand out"),
    (9, "tennis ball swing dangerous hoti hai"),
    (0, "umpire decision pe gussa mat karo TV pe"),
    (1, "impossible, that's the fun"),
    (2, "favorite player era?"),
    (3, "2011 world cup nostalgia forever"),
    (4, "youngster to watch this year?"),
    (5, "domestic circuit follow karo, gems milte hain"),
    (6, "stadium mein jaake dekha kabhi?"),
    (7, "ek baar, crowd energy alag level"),
    (8, "rain ruined match trauma"),
    (9, "DLS samajh aata hai kisi ko? 😅"),
    (0, "T20 too much slogging?"),
    (1, "entertainment ke liye perfect hai"),
    (2, "bowling ya batting talent?"),
    (3, "batting looks glamorous but depth chahiye"),
    (4, "last over thriller ya easy win?"),
    (5, "thriller, heart attack cricket"),
    (6, "cricket memes > actual analysis"),
    (7, "both have place in this bubble"),
    (8, "match today — who's watching"),
    (9, "group watch thread chalu rakho"),
    (0, "predict score under 180 ya over"),
    (1, "over on flat pitch"),
    (2, "chai ready, match shuru"),
]

MOVIE_BUFFS_USERS = [
    "BollywoodBuff", "OTTbinger", "MarvelFatigue", "CriticMode", "HorrorOnly",
    "SubtitlesOn", "PopcornReady", "WeekendRelease", "OldGold", "SpoilerPolice",
]

MOVIE_BUFFS_MESSAGES = [
    (0, "weekend pe kya dekhu, OTT ya theatre?"),
    (1, "theatre for big screen experience"),
    (2, "last movie that genuinely surprised you?"),
    (3, "Andhadhun rewatch pe bhi solid"),
    (4, "Bollywood 2024 — kuch accha aaya?"),
    (5, "mixed bag, regional cinema better lag rahi"),
    (6, "Hollywood blockbuster fatigue ho gaya"),
    (7, "same, small films >>>"),
    (8, "horror dekhte ho alone? brave"),
    (9, "lights on, volume low, still scared 😂"),
    (0, "subtitles always on gang"),
    (1, "missing dialogue = crime"),
    (2, "Marvel still worth it?"),
    (3, "selective, not every release"),
    (4, "underrated Hindi film rec?"),
    (5, "Panchayat if series count kare"),
    (6, "comfort rewatch — Zindagi Na Milegi Dobara"),
    (7, "DDLJ generation represent 🙋"),
    (8, "movie snacks — popcorn ya samosa"),
    (9, "samosa in interval, rule"),
    (0, "review padhke jaate ho ya blind?"),
    (1, "avoid reviews, spoilers hate"),
    (2, "actor driven ya story driven?"),
    (3, "story. always story."),
    (4, "Korean dramas entry point?"),
    (5, "Crash Landing on You classic"),
    (6, "documentary rec chahiye"),
    (7, "Free Solo if you haven't"),
    (8, "theatre etiquette: phone off please"),
    (9, "screen brightness in dark hall = villain"),
    (0, "friday release plans?"),
    (1, "might catch evening show"),
    (2, "spoiler mat dena trailer ke baad bhi"),
    (3, "spoiler police on duty 🚨"),
]

TRAVELERS_USERS = [
    "WeekendTrip", "Backpacker", "HiddenGem", "SoloTravel", "FoodTrail",
    "BudgetRoute", "TrekLover", "PhotoHunt", "MonsoonPlan", "LocalGuide",
]

TRAVELERS_MESSAGES = [
    (0, "weekend trip 2 din ke liye kahan ja sakte hain nearby?"),
    (1, "hill station agar weather clear ho"),
    (2, "solo trip safe lagta hai?"),
    (3, "day trips OK, inform someone always"),
    (4, "hidden place batao tourist trap nahi"),
    (5, "early morning local market explore karo"),
    (6, "trek difficulty easy wala chahiye"),
    (7, "sunrise trek worth the 4am alarm"),
    (8, "travel hack: off season mein jao"),
    (9, "hotels half price, crowd kam"),
    (0, "food discovery trips are the best trips"),
    (1, "street food map bana ke ghumo"),
    (2, "budget under 3k possible weekend?"),
    (3, "bus + homestay se ho jata hai"),
    (4, "monsoon travel risky ya beautiful?"),
    (5, "landslides check karo pehle"),
    (6, "camera ya phone enough for photos?"),
    (7, "phone mostly, DSLR optional"),
    (8, "last trip highlight drop karo"),
    (9, "unexpected sunset on highway, best moment"),
    (0, "travel buddy matching yahi bubble mein?"),
    (1, "plan thread start karte hain"),
    (2, "packing minimal tips?"),
    (3, "one bag challenge try karo"),
    (4, "train journey vs road trip vibe"),
    (5, "train for sleep + views"),
    (6, "homestay vs hotel experience"),
    (7, "homestay for local feel"),
    (8, "next month group trek interest?"),
    (9, "count me in if beginner friendly"),
]

CAFE_CONVERSATIONS_USERS = [
    "EspressoLover", "LatteArt", "RemoteWorker", "PeopleWatcher", "WifiHunter",
    "CornerSeat", "ColdBrew", "PastryFan", "MeetingSpot", "ChaiOverCoffee",
]

CAFE_CONVERSATIONS_MESSAGES = [
    (0, "best cafe for laptop work nearby?"),
    (1, "wifi strong + plugs wala corner chahiye"),
    (2, "cold brew ya hot latte today?"),
    (3, "cold brew, weather too hot"),
    (4, "people watching at cafes is underrated entertainment"),
    (5, "story lines invent karte hain mind mein 😂"),
    (6, "meeting spot cafe OK ya too noisy?"),
    (7, "morning quiet hours best"),
    (8, "pastry recommendation pls"),
    (9, "carrot cake if available, always"),
    (0, "chai > coffee fight start"),
    (1, "dono apni jagah pe, peace"),
    (2, "how long is too long to sit with one coffee"),
    (3, "2 hours if crowd nahi hai"),
    (4, "barista small talk enjoy ya awkward?"),
    (5, "short chat OK, long nahi"),
    (6, "window seat worth extra wait"),
    (7, "always, natural light for mood"),
    (8, "cafe hopping Sunday plan"),
    (9, "3 cafes, rating thread banate hain"),
    (0, "noise cancelling headphones must"),
    (1, "WFH cafe day weekly ritual"),
    (2, "overpriced coffee but vibe sells"),
    (3, "paying for ambience half the time"),
    (4, "date cafe vs solo cafe different picks"),
    (5, "solo = quiet, date = aesthetic"),
    (6, "funniest overheard conversation at cafe?"),
    (7, "someone pitching startup to date 😭"),
    (8, "new cafe discovery drop pin if ok"),
    (9, "corner table gang assemble"),
]

IIT_NIT_ASPIRANTS_USERS = [
    "JEEwarrior", "DropYear", "NCERTfan", "MockTest", "HostelDream",
    "RankFear", "PhysicsPain", "MathGenius", "MotivationLow", "SeniorBhai",
]

IIT_NIT_ASPIRANTS_MESSAGES = [
    (0, "mock score improve nahi ho raha, frustrate"),
    (1, "analysis karo mistakes ki, quantity mat badhao"),
    (2, "NCERT enough hai really?"),
    (3, "basics ke liye haan, advanced ke liye extra"),
    (4, "drop year worth it? serious answers"),
    (5, "gap explain karna padta hai, plan clear ho toh OK"),
    (6, "physics rotation chapter trauma"),
    (7, "same, mechanics strong banao pehle"),
    (8, "daily study hours kitne realistic?"),
    (9, "6-8 focused > 12 distracted"),
    (0, "motivation zero wale din kya karte ho"),
    (1, "short walk + one chapter only"),
    (2, "coaching ya self study?"),
    (3, "self study + online tests worked for me"),
    (4, "rank fear real hai ya exaggerated"),
    (5, "real hai but breathe, multiple paths hain"),
    (6, "hostel life stories sunao seniors"),
    (7, "maggi at 2am hits different"),
    (8, "college tier kitna matter long term"),
    (9, "skills + network matter more eventually"),
    (0, "revision strategy kya hai"),
    (1, "short notes + past mistakes notebook"),
    (2, "group study helpful ya distraction"),
    (3, "distraction if friends same energy 😂"),
    (4, "break schedule batao"),
    (5, "50 min study 10 min break"),
    (6, "parents pressure handle kaise"),
    (7, "honest talks + small wins share karo"),
    (8, "anyone giving mock today?"),
    (9, "all the best jo de rahe ho 🍀"),
    (0, "this bubble helps, less alone feel"),
    (1, "daily check-in thread rakhte hain?"),
    (2, "haan, subah goal post karo"),
]

# All community bubbles in seed order
COMMUNITY_BUBBLES = [
    {
        "title": "Book Worms Nearby 📚",
        "topic": "books, novels, self-help, fiction, reading habits and recommendations",
        "users": BOOK_WORMS_USERS,
        "messages": BOOK_WORMS_MESSAGES,
    },
    {
        "title": "Software Engineers Nearby 💻",
        "topic": "coding, interviews, startups, AI tools, remote jobs, tech memes, career growth",
        "users": SOFTWARE_ENGINEERS_USERS,
        "messages": SOFTWARE_ENGINEERS_MESSAGES,
    },
    {
        "title": "Startup Founders Nearby 🚀",
        "topic": "business ideas, product building, funding, growth, customer acquisition, founder struggles",
        "users": STARTUP_FOUNDERS_USERS,
        "messages": STARTUP_FOUNDERS_MESSAGES,
    },
    {
        "title": "Fitness Freaks Nearby 💪",
        "topic": "gym, running, diet, protein, weight loss, fitness motivation",
        "users": FITNESS_FREAKS_USERS,
        "messages": FITNESS_FREAKS_MESSAGES,
    },
    {
        "title": "Anime Fans Nearby 🎌",
        "topic": "anime recommendations, manga, new releases, character debates, memes",
        "users": ANIME_FANS_USERS,
        "messages": ANIME_FANS_MESSAGES,
    },
    {
        "title": "Cricket Lovers Nearby 🏏",
        "topic": "IPL, team selection, match predictions, players, funny cricket takes",
        "users": CRICKET_LOVERS_USERS,
        "messages": CRICKET_LOVERS_MESSAGES,
    },
    {
        "title": "Movie Buffs Nearby 🎬",
        "topic": "Bollywood, Hollywood, OTT releases, reviews, recommendations",
        "users": MOVIE_BUFFS_USERS,
        "messages": MOVIE_BUFFS_MESSAGES,
    },
    {
        "title": "Travelers Nearby ✈️",
        "topic": "weekend trips, hidden places, trekking, travel hacks, food discoveries",
        "users": TRAVELERS_USERS,
        "messages": TRAVELERS_MESSAGES,
    },
    {
        "title": "Cafe Conversations ☕",
        "topic": "coffee, cafes, workspaces, funny observations, people watching",
        "users": CAFE_CONVERSATIONS_USERS,
        "messages": CAFE_CONVERSATIONS_MESSAGES,
    },
    {
        "title": "IIT/NIT Aspirants Nearby 📖",
        "topic": "JEE prep, college life, study techniques, motivation, hostel stories",
        "users": IIT_NIT_ASPIRANTS_USERS,
        "messages": IIT_NIT_ASPIRANTS_MESSAGES,
    },
]

# fmt: on


def bubble_messages_as_json(bubble: dict) -> list[dict[str, str]]:
    """Export a bubble script as [{username, message}, ...] for API/fixtures."""
    users = bubble["users"]
    return [
        {"username": users[speaker_idx % len(users)], "message": text}
        for speaker_idx, text in bubble["messages"]
    ]


def all_bubbles_as_json() -> dict[str, list[dict[str, str]]]:
    """All community bubbles keyed by title."""
    return {b["title"]: bubble_messages_as_json(b) for b in COMMUNITY_BUBBLES}
