"""Shared demo bubble titles, personas, and AI topic hints."""

DEFAULT_LAT = 19.0760
DEFAULT_LNG = 72.8777

BUBBLE_TITLES = [
    "Best chai & coffee in town ☕",
    "Night hangout spots 🌙",
    "Weekend plan kya hai?",
    "Street food recommendations 🌮",
    "Bakwas lunch rant 😤",
]

LEGACY_DEMO_TITLES = [
    "Late night chai & baatein ☕",
    "Andheri metro crowd 🚇",
    "Best street food near me 🌮",
    "Internship / placement gyaan",
]

ALL_DEMO_TITLES = BUBBLE_TITLES + LEGACY_DEMO_TITLES

USER_POOLS = [
    ["ChaiLover", "FilterFan", "CuttingChai", "ColdBrew", "MasalaGirl", "IraniCafe", "OfficeChai", "LatteArt", "GingerTea", "EspressoBro"],
    ["NightOwl", "AfterHours", "MarineDrive", "RooftopGuy", "LiveMusic", "SafeSolo", "2amHungry", "ClubNoob", "WalkTalk", "StarGazer"],
    ["WeekendKing", "BrunchQueen", "Trekker", "MovieBuff", "Homebody", "Foodie", "BudgetTravel", "PoolParty", "Sleepyhead", "Spontaneous"],
    ["PavBhaji", "Momos4Life", "ChaatLover", "VadaPav", "DosaKing", "KebabFan", "SweetTooth", "SpiceLevel", "VegOnly", "MidnightBiryani"],
    ["CanteenVictim", "TiffinFail", "MaggiForever", "SaladSad", "HRlunch", "WfhEater", "SkipLunch", "Cafeteria", "HangryDev", "MealPrep"],
]

# Short topic line for AI system prompts (index matches BUBBLE_TITLES)
TOPIC_PROMPTS = [
    "finding the best chai and coffee in town — tapri vs cafe, cutting chai, filter coffee",
    "night hangout spots — safe late-night places, Marine Drive, food after midnight",
    "weekend plans — trips, brunch, movies, treks, budget ideas",
    "street food — vada pav, chaat, momos, hygiene tips, best stalls",
    "complaining about bad office/canteen lunch — bakwas khana, tiffin fails, maggi survival",
]

DEMO_ONLINE_COUNT = 10

# (speaker_index, message) per bubble — Hindi/English mix
CONVERSATIONS = [
    [
        (0, "Guys serious debate — best cutting chai in town kahan milti hai?"),
        (1, "Filter coffee South Indian joints pe jeet jaati hai, chai ke liye tapri."),
        (2, "Tapri near station — adrak strong, half cup ₹10. Peak."),
        (3, "Coffee mein Blue Tokai ya local roastery try ki hai kisi ne?"),
        (4, "Local roastery better value. Blue Tokai weekend queue nightmare."),
        (5, "Masala chai vs normal chai — kitna masala is too much?"),
        (6, "Elaichi overdose = perfume cup 😂 thoda hi sahi."),
        (7, "Genuine question: chai bag wali ya fresh patti — taste difference real?"),
        (8, "Fresh patti always. Bag wali office emergency only."),
        (9, "Cold coffee summer mein bhi chai peete ho ya switch?"),
        (0, "Switch nahi — cutting chai garam hi chahiye year round."),
        (1, "Irani cafe bun maska + chai combo — underrated?"),
        (2, "Highly underrated. Breakfast of champions."),
        (3, "Best coffee under ₹150? Student budget friendly."),
        (4, "Cappuccino at small cafes — ask for double shot, still cheap."),
        (5, "Chai pe charcha — do you judge people by tea vs coffee team?"),
        (6, "Nahi yaar, dono valid. Main dono peeta hun."),
        (7, "Night shift — chai kitni cup max? Meri record 7 hai 💀"),
        (8, "After 4 I get anxiety. Green tea switch karo."),
        (9, "Okay vote: tapri chai > fancy cafe?"),
        (0, "Tapri for soul. Cafe for laptop and WiFi."),
        (1, "Thanks — ab chai peene ja raha hun, recommendations solid thi ✌️"),
    ],
    [
        (0, "Aaj raat kahan hangout kar sakte hain? Safe + fun chahiye."),
        (1, "Marine Drive walk — free, open, couples + friends dono."),
        (2, "Rooftop cafe after 10 — vibe achhi but pricey."),
        (3, "Solo jaana safe hai kya late night? Genuine question."),
        (4, "Crowded public spots OK. Empty lanes avoid. Share live location."),
        (5, "Best time for night drive — 11 pm ya 1 am?"),
        (6, "11 pm traffic kam. 1 am feels cinematic but sleepy drivers."),
        (7, "Live music wala spot koi batao is week."),
        (8, "Check Instagram stories of local bars — guest list scene."),
        (9, "Food after midnight — kya open rehta hai seriously?"),
        (0, "Shawarma spots, some McD 24h, and the legendary anda pav stall."),
        (1, "Club jaana hai first time — entry scene kaisa hota hai?"),
        (2, "Cover charge + ID. Prebook if popular night."),
        (3, "Budget hangout under ₹500 per person — ideas?"),
        (4, "Beach + street food + auto ride. Done."),
        (5, "Late night chai tapri pe baith ke gossip > club any day."),
        (6, "Star gazing spot outskirts pe — worth the drive?"),
        (7, "Haan if weather clear. Mosquito repellent le lena 😅"),
        (8, "Curfew ya police hassle hota hai kya area mein?"),
        (9, "Generally fine if not creating noise. Respect locals."),
        (0, "Plan set — Marine Drive 10:30, phir cutting chai. Who's in?"),
        (1, "In. Late night gang assemble 🌙"),
    ],
    [
        (0, "Weekend plan kya hai sabka? Main abhi bhi clueless."),
        (1, "Saturday trek, Sunday lazy + laundry. Classic."),
        (2, "Friend ne Goa bol diya — budget kitna realistic for 2 days?"),
        (3, "₹5-8k per person if bus + hostel. Flight alag story."),
        (4, "Movie ya web series binge — theatre worth it?"),
        (5, "Theatre for big releases. OTT for comfort."),
        (6, "Day trip near city — Alibaug / Lonavala type?"),
        (7, "Ferry + beach = solid without burning leave."),
        (8, "House party vs going out — team kya?"),
        (9, "House party. Playlist + snacks split."),
        (0, "Brunch overrated hai ya worth it once a month?"),
        (1, "Worth it for catch-up. Photo tax included 😂"),
        (2, "Gym skip karke weekend full rest — guilty feel hota hai?"),
        (3, "Rest bhi recovery hai. Monday se phir."),
        (4, "Random: best Sunday market for cheap shopping?"),
        (5, "Local flea markets — bargain skills mandatory."),
        (6, "Family obligation vs friends plan — kaise balance?"),
        (7, "Half day family, half day friends. Negotiate 😅"),
        (8, "Main toh ghar pe gaming + biryani. Zero regrets."),
        (9, "Solid plans everyone — Monday update dena gossip ke liye!"),
        (0, "Done. Enjoy weekend all 🙌"),
    ],
    [
        (0, "Street food recommendations chahiye — veg + non-veg dono."),
        (1, "Vada pav near station — Mumbai religion."),
        (2, "Paneer tikka roll — underrated street gem."),
        (3, "Hygiene kaise judge karte ho stall pe? Genuine question."),
        (4, "Crowd + turnover + gloves/tongs. Busy stall usually fresher."),
        (5, "Momos steamed ya fried? Team?"),
        (6, "Steamed + red chutney. Fight me."),
        (7, "Best chaat — bhel ya pani puri?"),
        (8, "Pani puri live counter — entertainment + taste."),
        (9, "Budget ₹200 mein kya khana fill karega?"),
        (0, "Pav bhaji plate + soda. Done."),
        (1, "Late night street food safe hai?"),
        (2, "Busy areas OK. Odd empty stall at 3 am — skip."),
        (3, "Spice level 'medium' bolna — still fire milta hai 😭"),
        (4, "Bolta hai 'thoda kam mirchi' — vendor smiles and ignores."),
        (5, "Sweet ending — kulfi ya gola?"),
        (6, "Kulfi falooda if feeling fancy on street."),
        (7, "Which city has best street food overall? Fight in chat."),
        (8, "Delhi vs Mumbai vs Kolkata — all have cases."),
        (9, "I'm ordering pani puri. 6 plates. No regrets."),
        (0, "Legend. Report back taste review 🙏"),
    ],
    [
        (0, "Aaj ka lunch itna bakwas tha ki ab mood off hai 😤"),
        (1, "Same. Office canteen ne betray kar diya."),
        (2, "Kya mila? Dal pani jaisa ya dry roti?"),
        (3, "Soggy rice + mystery sabzi. Color suspicious."),
        (4, "Tiffin leak + taste fail — double trauma."),
        (5, "Genuine question: skip lunch or force eat bad food?"),
        (6, "Skip + 4 pm maggi. Survival mode."),
        (7, "Cafeteria 'special' pe trust mat karo — lesson learned."),
        (8, "WFH lunch = last night's leftover — better than canteen?"),
        (9, "Always. Canteen is roulette."),
        (0, "HR ne healthy salad push kiya — tastes like sadness."),
        (1, "Salad mein dressing bhi cheap. Double bakwas."),
        (2, "Best revenge — ghar pe achha dinner plan karo."),
        (3, "Swiggy order kiya compensatory biryani. No guilt."),
        (4, "Meal prep Sunday karta hun phir bhi Wednesday sad ho jata hai."),
        (5, "Sharing tiffin with colleague — risk ya bonding?"),
        (6, "Bonding until they take your last paratha."),
        (7, "School lunch nostalgia > adult lunch reality."),
        (8, "Adult lunch = meetings during chew. Rude."),
        (9, "Kal se tiffin ghar se. Declaration in chat for accountability."),
        (0, "Support group ban gaya ye bubble 😂 same guys tomorrow?"),
        (1, "Haan. Lunch rant daily thread chalega."),
    ],
]
