"""
Demo/onboarding seed content for seed_demo_content management command.

All personas and dialogue are fictional demo material — not real users.
"""

from __future__ import annotations

DEFAULT_LAT = 20.96
DEFAULT_LNG = 77.768

# speaker index, text, optional image label
MessageLine = tuple[int, str] | tuple[int, str, str]

SEED_COMMUNITY_TITLES: list[str] = [
    "Book Readers Club",
    "Software Engineers",
    "Startup Founders",
    "Fitness Enthusiasts",
    "Anime Fans",
    "Coffee Lovers",
    "Movie Discussions",
    "Cricket Fans",
    "Travelers Community",
    "English Speaking Practice",
    "Local Foodies",
    "Job Seekers Network",
    "College Students Hub",
    "Photography Lovers",
    "Music & Guitar Club",
]

SEED_COMMUNITIES: list[dict] = [
    {
        "title": "Book Readers Club",
        "users": [
            "PageTurner", "MidnightReader", "KindleFan", "FictionLover", "PoetryNerd",
            "AudiobookGuy", "LibraryGhost", "SpoilerAlert", "BookmarkChaos", "SelfHelpSkeptic",
        ],
        "messages": [
            (0, "koi achhi fiction recommend karo yaar, thriller type"),
            (1, "The Silent Patient try karo — twist solid hai"),
            (2, "main audiobook pe shift ho gaya, commute pe easy rehta hai"),
            (3, "audiobook se story feel thodi kam hoti hai mere liye 😅"),
            (4, "self help books kabhi overrated lagte hain"),
            (5, "Atomic Habits ne genuinely help kiya though"),
            (0, "physical book vs kindle — team kya?"),
            (6, "kindle for travel, physical for home vibe"),
            (7, "spoiler mat dena koi 👀 half pe hun main"),
            (8, "Indian author suggestion? English ya Hindi dono chalega"),
            (9, "Ruskin Bond short stories underrated hain"),
            (1, "currently reading Project Hail Mary — sci-fi fans?"),
            (2, "Andy Weir fan ✋ same book almost done"),
            (3, "book club join kiya kisi ne kabhi?"),
            (4, "college mein try kiya, sab ne last minute skip 😂"),
            (5, "online book clubs better hain ab"),
            (6, "mera current shelf — thoda messy but happy", "books"),
            (7, "nice collection! main library card ab bhi use karta hun"),
            (8, "Sunday chai + reading ritual best hai"),
            (9, "non-fiction streak 10 days chal rahi 🔥"),
            (0, "book exchange nearby karte hain kya? 📚"),
        ],
    },
    {
        "title": "Software Engineers",
        "users": [
            "CodeNinja", "BugHunter", "RemoteDev", "StackOverflow", "NightOwlDev",
            "InterviewPrep", "StartupCoder", "MemeDev", "GitPush", "DevOpsDude",
        ],
        "messages": [
            (0, "Cursor vs VS Code — serious question"),
            (1, "Cursor hype chal raha hai, VS Code still solid"),
            (2, "remote job scene kaisa hai ab?"),
            (3, "better than 2023 imo, openings aa rahi hain"),
            (4, "DSA grind kab khatam hoga yaar"),
            (5, "never ends bro, accept kar lo 😂"),
            (6, "production bug 2am pe aaya, classic"),
            (7, "git blame dekh ke regret hota hai"),
            (0, "Python vs JS backend — fight start"),
            (1, "use case pe depend, dono seekho"),
            (2, "system design tips koi share karega?"),
            (3, "YouTube concepts + mock interviews help kiye"),
            (4, "Leetcode daily karte ho?"),
            (5, "3-4 problems week mein realistic lagta hai"),
            (6, "mera WFH setup finally sort ho gaya", "coding"),
            (7, "dual monitor life changed everything"),
            (8, "startup mein sab kuch JS mein ho jata hai"),
            (9, "tech stack wars bore ho gaye honestly"),
            (0, "CI/CD pipeline simplify kaise karte ho?"),
            (1, "GitHub Actions se start karo, baad mein optimize"),
        ],
    },
    {
        "title": "Startup Founders",
        "users": [
            "FounderOne", "PitchDeck", "BootstrapBoss", "VCChaser", "ProductPM",
            "GrowthHacker", "BurnRate", "CofounderHunt", "MVPBuilder", "PivotKing",
        ],
        "messages": [
            (0, "idea validate kaise karte ho pehle?"),
            (1, "10 customer interviews — non negotiable"),
            (2, "bootstrap vs funding — kya sochte ho?"),
            (3, "bootstrap agar runway tight ho"),
            (4, "pitch deck mein sabse common mistake?"),
            (5, "too much text, not enough story"),
            (0, "cofounder dhundhna itna hard kyun hai 😅"),
            (1, "complementary skills + same values matter"),
            (2, "MVP kitne features ke saath launch kiya?"),
            (3, "ek core problem, ek flow — bas"),
            (4, "first 100 users kaise mile?"),
            (5, "personal network + local communities like this"),
            (6, "burn rate track karte ho daily?"),
            (7, "weekly sheet enough hai early stage pe"),
            (8, "pivot kiya kabhi? experience share karo"),
            (9, "haan, 6 months baad direction change — best decision"),
            (0, "B2B ya B2C — kis mein zyada opportunity?"),
            (1, "depends on market, dono mein winners hain"),
            (2, "legal/compliance early pe ignore mat karo"),
            (3, "learned the hard way on contracts"),
            (4, "demo day nerves normal hain yaar"),
            (5, "practice pitch 20 times, phir bhi nervous 😂"),
        ],
    },
    {
        "title": "Fitness Enthusiasts",
        "users": [
            "GymRat", "ProteinShake", "MorningRun", "YogaFlow", "CalorieCount",
            "LegDay", "RestDay", "HomeWorkout", "MarathonPrep", "FitFam",
        ],
        "messages": [
            (0, "gym 6am ya 8pm — kya better hai?"),
            (1, "jo time consistently ho sake wahi best"),
            (2, "protein intake kitna lete ho daily?"),
            (3, "body weight ke hisaab se ~1.6g/kg try karta hun"),
            (4, "home workout effective hai ya gym must?"),
            (5, "dumbbells + discipline se bhi results aate hain"),
            (0, "leg day skip mat karo guys 😂"),
            (1, "never skip leg day mantra"),
            (2, "yoga + weights combo kaise hai?"),
            (3, "mobility improve hui meri"),
            (4, "running ke baad knee pain — tips?"),
            (5, "proper shoes + gradual mileage increase"),
            (6, "30 day challenge join karein?"),
            (7, "I'm in — accountability group"),
            (8, "progress pic share karu? motivation ke liye", "gym"),
            (9, "go for it, community support helps"),
            (0, "rest day guilty feel hota hai kisi ko?"),
            (1, "recovery bhi training ka part hai"),
            (2, "meal prep Sunday ritual worth it hai"),
            (3, "time bachta hai week mein"),
            (4, "creatine use karte ho?"),
            (5, "simple aur effective lagta hai research mein"),
            (6, "steps target 10k realistic?"),
            (7, "8k bhi achha start hai"),
        ],
    },
    {
        "title": "Anime Fans",
        "users": [
            "OtakuLife", "MangaReader", "WaifuWatcher", "SubNotDub", "CosplayNewb",
            "ShonenFan", "SliceOfLife", "AMVEditor", "FigureCollector", "EpisodeOne",
        ],
        "messages": [
            (0, "current season mein kya dekh rahe ho?"),
            (1, "Frieren aur kuch isekai mix"),
            (2, "sub vs dub — team?"),
            (3, "sub original vibes ke liye"),
            (4, "pehla anime kya tha tumhara?"),
            (5, "Naruto classic entry point 😄"),
            (0, "manga padhte ho ya sirf anime?"),
            (1, "donon — manga aage hota hai often"),
            (2, "cosplay try kiya kabhi?"),
            (3, "comicon pe simple cosplay kiya, fun tha"),
            (4, "underrated anime recommendation do"),
            (5, "March Comes in Like a Lion — emotional masterpiece"),
            (6, "figure collection dikhau? shelf full ho gayi", "anime"),
            (7, "jealous 😂 kitne saal se collect kar rahe ho?"),
            (8, "AMV editing seekhna chahta hun"),
            (9, "DaVinci Resolve free hai, tutorials dekh lo"),
            (0, "one piece length se darte ho?"),
            (1, "start karo, worth it hai trust"),
            (2, "studio Ghibli marathon when?"),
            (3, "weekend plan bana sakte hain"),
            (4, "spoiler culture toxic ho jati hai kabhi"),
            (5, "agree — new fans ko space do"),
            (6, "favourite opening theme?"),
            (7, "too many to pick one honestly"),
        ],
    },
    {
        "title": "Coffee Lovers",
        "users": [
            "EspressoFan", "LatteArt", "ColdBrew", "CafeHopper", "BeanGeek",
            "DecafOnly", "MorningBrew", "FrenchPress", "BaristaDream", "CaffeineFix",
        ],
        "messages": [
            (0, "best filter coffee nearby kaun sa?"),
            (1, "corner wala naya place try kiya — solid"),
            (2, "home brewing setup kaisa hai?"),
            (3, "French press + hand grinder — simple aur good"),
            (4, "latte art seekhna chahta hun 😅"),
            (5, "YouTube pe basic heart shape se start"),
            (0, "cold brew vs iced coffee difference?"),
            (1, "brew method alag hai, taste bhi"),
            (2, "remote work ke liye quiet cafe suggest karo"),
            (3, "library ke paas wala kam crowded rehta hai"),
            (4, "decaf drinkers assemble 🙋"),
            (5, "evening cup ke liye decaf best"),
            (6, "aaj ki latte attempt — thoda progress", "coffee"),
            (7, "not bad! steam milk thoda aur practice"),
            (8, "single origin beans kahan milte hain?"),
            (9, "local roaster try karo, fresh milta hai"),
            (0, "cafe hopping Sunday plan?"),
            (1, "3 cafes list bana dete hain"),
            (2, "overpriced coffee rant — but still buy it 😂"),
            (3, "experience ke liye kabhi kabhi ok hai"),
            (4, "coconut milk latte underrated hai"),
            (5, "plant based options badh rahe hain thankfully"),
        ],
    },
    {
        "title": "Movie Discussions",
        "users": [
            "FilmBuff", "SpoilerFree", "MarvelFan", "IndieCinema", "HorrorNight",
            "BollywoodBinge", "OTTWatcher", "CriticMode", "PopcornReady", "DirectorCut",
        ],
        "messages": [
            (0, "last weekend kya dekha?"),
            (1, "theatre mein ek action film — mindless fun"),
            (2, "OTT pe koi hidden gem?"),
            (3, "Korean thriller try karo agar nahi dekha"),
            (4, "Marvel fatigue real hai kya?"),
            (5, "thodi hai but big screen pe still fun"),
            (0, "Bollywood vs Hollywood preference?"),
            (1, "story pe depend, label se nahi"),
            (2, "horror dekh sakte ho alone?"),
            (3, "nahi yaar lights on rehti hain 😂"),
            (4, "favourite director?"),
            (5, "too many — Nolan, Zoya, Denis Villeneuve"),
            (6, "cinema hall experience ya home?"),
            (7, "theatre for big releases, home for rewatch"),
            (8, "movie review spoilers dete hain — pet peeve"),
            (9, "spoiler free reviews best hain"),
            (0, "underrated Bollywood 2020s?"),
            (1, "several small films OTT pe achhi hain"),
            (2, "popcorn sweet ya salted?"),
            (3, "mixed bucket always"),
            (4, "interstellar rewatch kabhi kabhi must"),
            (5, "Hans Zimmer score 🔥"),
            (6, "film club banate hain kya monthly?"),
            (7, "good idea — rotate hosts"),
        ],
    },
    {
        "title": "Cricket Fans",
        "users": [
            "CoverDrive", "YorkerKing", "IPLFanatic", "TestMatch", "FantasyXI",
            "GullyCricket", "CommentaryFan", "StatsNerd", "TeamIndia", "WeekendLeague",
        ],
        "messages": [
            (0, "aaj ka match dekha?"),
            (1, "last over tak tension thi"),
            (2, "Test cricket still best format?"),
            (3, "purists ke liye yes, T20 mass appeal"),
            (4, "fantasy team tips do yaar"),
            (5, "form + pitch report dono dekho"),
            (0, "favourite player current gen?"),
            (1, "too hard to pick one"),
            (2, "gully cricket memories share karo"),
            (3, "tennis ball se window break classic 😂"),
            (4, "IPL team loyalty fixed hai?"),
            (5, "childhood se same team"),
            (6, "stadium jana worth it hai?"),
            (7, "ek baar live atmosphere alag hi hai"),
            (8, "match day snacks ritual?"),
            (9, "samosa + chai mandatory"),
            (0, "who wins today — predictions?"),
            (1, "no jinx please 🙏"),
            (2, "stats say close game"),
            (3, "numbers vs heart — heart wins often"),
            (4, "local league khelte ho weekend pe?"),
            (5, "Sunday morning turf booking"),
            (6, "highlights ya full replay?"),
            (7, "highlights busy day pe, full when free"),
        ],
    },
    {
        "title": "Travelers Community",
        "users": [
            "Wanderlust", "Backpacker", "SoloTrip", "BudgetTravel", "RoadTrip",
            "MountainLover", "BeachBum", "TravelPhoto", "LocalGuide", "WeekendEscape",
        ],
        "messages": [
            (0, "next trip plan kya hai?"),
            (1, "mountains — short 3 day break"),
            (2, "solo travel safe tips?"),
            (3, "research + daytime travel + share location"),
            (4, "budget trip under 5k possible?"),
            (5, "nearby places se start karo"),
            (0, "favourite trip ab tak?"),
            (1, "coastal road trip last year — unforgettable"),
            (2, "packing light kaise karte ho?"),
            (3, "capsule wardrobe + one pair extra shoes"),
            (4, "monsoon travel recommend?"),
            (5, "green landscapes but plan for delays"),
            (6, "recent trek photo — views insane the", "travel"),
            (7, "wow which trail?"),
            (8, "homestay vs hotel — preference?"),
            (9, "homestay for local food + stories"),
            (0, "travel buddy dhundhna easy nahi"),
            (1, "communities like this help actually"),
            (2, "weekend getaway ideas nearby?"),
            (3, "hill station 2-3 hours drive list bana sakte hain"),
            (4, "travel insurance lete ho?"),
            (5, "long trips pe yes, short pe skip sometimes"),
            (6, "vlog ya enjoy the moment?"),
            (7, "few photos then phone away"),
        ],
    },
    {
        "title": "English Speaking Practice",
        "users": [
            "FluentSoon", "GrammarFix", "AccentEase", "DailyPractice", "Toastmaster",
            "InterviewEnglish", "MovieLearner", "WordOfDay", "ShySpeaker", "DebateClub",
        ],
        "messages": [
            (0, "daily practice routine share karo"),
            (1, "15 min loud reading + 5 min self talk"),
            (2, "accent improve karna hai — tips?"),
            (3, "shadowing podcasts helps a lot"),
            (4, "grammar weak hai — kya karein?"),
            (5, "Grammarly + short journaling daily"),
            (0, "group call practice karte hain?"),
            (1, "Sunday evening 30 min session?"),
            (2, "interview English alag lagta hai"),
            (3, "STAR format answers practice karo"),
            (4, "movies se sikhna effective hai?"),
            (5, "subtitles on, then off — gradual"),
            (6, "word of the day: articulate"),
            (7, "use it in a sentence challenge?"),
            (8, "main shy hun bolte waqt — normal?"),
            (9, "bilkul — small groups se start karo"),
            (0, "topic for tomorrow: describe your city"),
            (1, "good prompt, I'll prepare"),
            (2, "mistakes pe log judge karte hain?"),
            (3, "yahan safe space hai practice ke liye"),
            (4, "record yourself — cringe but useful"),
            (5, "heard my filler words umm a lot 😅"),
            (6, "slow down, clarity > speed"),
            (7, "thanks, will try tonight"),
        ],
    },
    {
        "title": "Local Foodies",
        "users": [
            "StreetFoodie", "HomeChef", "SpiceLevel", "SweetTooth", "VegOnly",
            "BiryaniJudge", "FoodBlogger", "MidnightSnack", "ThaliLover", "NewCafeAlert",
        ],
        "messages": [
            (0, "best street food spot nearby?"),
            (1, "market ke corner wala pav bhaji solid"),
            (2, "biryani ranking thread start 😂"),
            (3, "spicy layer + raita balance matters"),
            (4, "home cooked comfort food kya hai?"),
            (5, "dal chawal with ghee — unbeatable"),
            (0, "new cafe try kiya kisi ne?"),
            (1, "opened last week — pasta decent tha"),
            (2, "veg options kam jagah pe problem"),
            (3, "thali places usually safe bet"),
            (4, "midnight hunger gang 🙋"),
            (5, "maggi upgrade: cheese + egg"),
            (6, "aaj ka lunch — homemade thali", "food"),
            (7, "looks amazing, recipe share?"),
            (8, "food blog start karna chahta hun"),
            (9, "phone camera enough hai start ke liye"),
            (0, "spice level tolerance?"),
            (1, "medium plus for me"),
            (2, "dessert after spicy meal necessary"),
            (3, "kulfi fi fix"),
            (4, "food delivery vs cook at home split?"),
            (5, "weekdays delivery, weekend cook"),
            (6, "regional dish recommendation do"),
            (7, "local specialty try karo pehle"),
        ],
    },
    {
        "title": "Job Seekers Network",
        "users": [
            "ResumeFix", "LinkedInPro", "ReferralPlease", "CareerSwitch", "FreshGrad",
            "HRInsider", "RemoteHunt", "InterviewLog", "SalaryTalk", "PortfolioDev",
        ],
        "messages": [
            (0, "resume review koi help karega?"),
            (1, "DM structure — 1 page better for early career"),
            (2, "referral kaise maange politely?"),
            (3, "specific role + short note + resume ready"),
            (4, "career switch 28 pe — too late?"),
            (5, "not at all, skills + projects matter"),
            (0, "LinkedIn headline tips?"),
            (1, "role + impact, not just job title"),
            (2, "fresh grad first job scene?"),
            (3, "internships + github + patience"),
            (4, "remote roles competition zyada hai"),
            (5, "timezone overlap highlight karo"),
            (6, "interview rejection cope kaise?"),
            (7, "feedback maango, next prep better"),
            (8, "salary negotiation uncomfortable lagta hai"),
            (9, "research range beforehand — practice lines"),
            (0, "portfolio projects ideas for devs?"),
            (1, "small useful app > tutorial clone"),
            (2, "mock interview partner chahiye"),
            (3, "weekend slot fix kar sakte hain"),
            (4, "HR round mein kya puchte hain?"),
            (5, "culture fit + situational questions"),
            (6, "job alert fatigue real hai"),
            (7, "curated list + 5 apps daily max"),
        ],
    },
    {
        "title": "College Students Hub",
        "users": [
            "SemesterSurvivor", "HostelLife", "ExamMode", "CampusEvents", "InternHunt",
            "GroupProject", "CanteenChat", "NotesShare", "FreshersWeek", "PlacementPrep",
        ],
        "messages": [
            (0, "exam schedule aa gaya — panic mode"),
            (1, "timetable bana lo abhi se"),
            (2, "hostel mess food predictable 😅"),
            (3, "Sunday outing balance important"),
            (4, "group project mein free riders — help"),
            (5, "roles assign karo written mein"),
            (0, "campus event koi interesting?"),
            (1, "tech fest next month"),
            (2, "notes share thread useful hoga?"),
            (3, "google drive link pinned kar sakte hain"),
            (4, "internship first year possible?"),
            (5, "small projects + outreach try karo"),
            (6, "library ya room — padhai kahan?"),
            (7, "library for focus, room for comfort"),
            (8, "canteen chai breaks mandatory"),
            (9, "social battery recharge"),
            (0, "placement prep kab start?"),
            (1, "second year se basics slow pace"),
            (2, "seniors se guidance lo"),
            (3, "mentorship matters a lot"),
            (4, "part time side hustle ideas?"),
            (5, "tutoring, design, dev freelancing"),
            (6, "fest volunteer fun experience tha"),
            (7, "networking unexpected benefit"),
        ],
    },
    {
        "title": "Photography Lovers",
        "users": [
            "ShutterBug", "GoldenHour", "StreetShot", "PortraitPro", "MobilePhoto",
            "RAWEdit", "LensNerd", "DronePilot", "FilmGrain", "CompositionGeek",
        ],
        "messages": [
            (0, "beginner camera budget 40k — suggestions?"),
            (1, "used body + kit lens se start ok hai"),
            (2, "mobile photography underrated hai"),
            (3, "latest phones computational magic karte hain"),
            (4, "golden hour spot nearby?"),
            (5, "river side walk last hour before sunset"),
            (0, "street photography courage kaise laaye?"),
            (1, "start from behind, candid distant shots"),
            (2, "RAW vs JPEG for learning?"),
            (3, "RAW forgiveness editing mein zyada"),
            (4, "editing app preference?"),
            (5, "Lightroom mobile free tier enough start ke liye"),
            (6, "aaj ki golden hour attempt", "camera"),
            (7, "composition clean hai, nice"),
            (8, "portrait lens worth it?"),
            (9, "50mm prime sweet spot budget mein"),
            (0, "photo walk Sunday plan?"),
            (1, "6am meet, soft light"),
            (2, "drone rules yaad rakho local area mein"),
            (3, "permissions check karna important"),
            (4, "film simulation presets use karte ho?"),
            (5, "subtle grain aesthetic pasand hai"),
            (6, "critique thread helpful rahega?"),
            (7, "constructive feedback culture build karte hain"),
        ],
    },
    {
        "title": "Music & Guitar Club",
        "users": [
            "AcousticSoul", "TabReader", "ChordProgress", "VocalWarmup", "BandHunt",
            "PianoToo", "CoverSong", "OpenMic", "RiffMaster", "Metronome",
        ],
        "messages": [
            (0, "beginner guitar — acoustic ya electric?"),
            (1, "acoustic fingers strong banate hain pehle"),
            (2, "sore fingers normal hai start mein?"),
            (3, "haan 2 weeks baad adjust ho jata hai"),
            (4, "daily practice kitna realistic?"),
            (5, "20-30 min consistent > 2 hour random"),
            (0, "favourite chord progression?"),
            (1, "Am F C G — classic emotional vibe"),
            (2, "singing + guitar together tough hai"),
            (3, "metronome se slow start karo"),
            (4, "band members dhundhna chahta hun"),
            (5, "drummer sabse rare commodity 😂"),
            (6, "aaj ka practice corner setup", "guitar"),
            (7, "cozy! interface bhi hai?"),
            (8, "cover song suggestions easy level?"),
            (9, "Knocking on Heaven's Door — 3 chords"),
            (0, "open mic experience kaisa raha?"),
            (1, "nervous but crowd supportive thi"),
            (2, "online tabs reliable sites?"),
            (3, "ultimate guitar + verify by ear"),
            (4, "music theory necessary?"),
            (5, "helpful but not mandatory to start"),
            (6, "fingerstyle ya strumming pehle?"),
            (7, "strumming patterns se rhythm build"),
        ],
    },
]

SEED_QUESTIONS: list[dict] = [
    {
        "title": "Best coffee shop for remote work?",
        "description": "Need decent WiFi, plugs, and not too loud on weekdays. Budget-friendly preferred.",
        "author": "RemoteWorker",
        "bubble_title": "Coffee Lovers",
        "answers": [
            ("CafeHopper", "Library ke paas wala cafe try karo — WiFi stable hai aur weekday pe quiet rehta hai."),
            ("BeanGeek", "Corner table maang lena, headphones lagao. Main wahan 3-4 hours easily rehta hun."),
            ("MorningBrew", "Second floor wala kam crowded hai. Chai refill reasonable price pe milti hai."),
            ("EspressoFan", "Avoid Saturday afternoon — student crowd zyada hoti hai."),
            ("LatteArt", "Power outlet window seat pe limited hai, early jao 9am se pehle."),
            ("DecafOnly", "If dead silent chahiye toh actual library better, cafe mein halka background music rehta hai."),
        ],
    },
    {
        "title": "Any React developers nearby?",
        "description": "Building a side project, looking for someone to pair on weekends. Not a job post — just learning.",
        "author": "FrontendNewbie",
        "bubble_title": "Software Engineers",
        "answers": [
            ("CodeNinja", "React + TS use karta hun — weekend slot ho sakta hai."),
            ("RemoteDev", "Discord/Meet pe pair programming ok hai. DM kar sakte ho approach kaise karein."),
            ("StackOverflow", "Start with small component library — easier to collaborate."),
            ("NightOwlDev", "Main Next.js zyada use karta hun but React core same hai."),
            ("MemeDev", "Pehle repo structure clear karo warna merge conflicts se friendship khatam 😂"),
            ("GitPush", "Open source style commits + PR reviews good practice rahega."),
        ],
    },
    {
        "title": "Good beginner books for investing?",
        "description": "Complete beginner, want to understand basics before touching mutual funds.",
        "author": "CuriousSaver",
        "bubble_title": "Book Readers Club",
        "answers": [
            ("SelfHelpSkeptic", "Rich Dad Poor Dad popular hai but take with grain of salt."),
            ("PageTurner", "The Psychology of Money — readable aur practical dono."),
            ("KindleFan", "Indian context ke liye blogs + RBI basics padh lo pehle."),
            ("FictionLover", "One book at a time, jargon google karte jao."),
            ("LibraryGhost", "Library mein personal finance section underrated hai — free."),
            ("AudiobookGuy", "Podcast 'Finshots' short episodes se start kar sakte ho."),
            ("BookmarkChaos", "Don't rush into stock tips from Telegram groups please 🙏"),
        ],
    },
    {
        "title": "Which gym would you recommend?",
        "description": "Looking for decent equipment, not insanely crowded 7-9pm. Budget ~1500/month.",
        "author": "NewToFitness",
        "bubble_title": "Fitness Enthusiasts",
        "answers": [
            ("GymRat", "Check trial day pe evening crowd — sab gyms alag behave karte hain."),
            ("LegDay", "Municipal stadium gym sasta hai but crowded — early morning better."),
            ("HomeWorkout", "If budget tight, dumbbells home + YouTube = workable."),
            ("ProteinShake", "Look for squat rack availability, bahut jagah sirf machines hain."),
            ("YogaFlow", "Hygiene matters — shower/locker check karo pehle."),
            ("MorningRun", "7-9 peak hai almost everywhere, 6am slot golden hai."),
            ("RestDay", "Annual plan pe discount milta hai usually, monthly try pehle."),
        ],
    },
    {
        "title": "Affordable coworking spaces nearby?",
        "description": "Need 2-3 days/week desk, meeting room occasionally. Startup budget.",
        "author": "BootstrapFounder",
        "bubble_title": "Startup Founders",
        "answers": [
            ("BootstrapBoss", "Shared desk monthly ~3-4k area pe depend karta hai."),
            ("MVPBuilder", "Cafe hopping free but inconsistent — coworking worth it for calls."),
            ("FounderOne", "Some spaces student discount dete hain — puchna mat bhoolo."),
            ("ProductPM", "Day pass leke pehle test karo vibe."),
            ("GrowthHacker", "Meeting room hourly rate alag hota hai — terms read karo."),
            ("CofounderHunt", "Library free alternative hai agar calls kam hain."),
        ],
    },
    {
        "title": "Best place to learn spoken English?",
        "description": "Hindi medium background, want conversational confidence for interviews.",
        "author": "ShySpeaker",
        "bubble_title": "English Speaking Practice",
        "answers": [
            ("DailyPractice", "App se nahi, bolna padega — yahi group weekly calls try karo."),
            ("AccentEase", "Mirror + record yourself — cringe but works."),
            ("MovieLearner", "English series with subtitles off gradually."),
            ("Toastmaster", "Local toastmasters club agar hai toh structured practice milti hai."),
            ("InterviewEnglish", "Mock interviews with friends — STAR format answers."),
            ("GrammarFix", "Mistakes normal hain, fluency pe focus karo pehle."),
            ("WordOfDay", "Think in English small sentences whole day."),
            ("FluentSoon", "15 min daily > 2 hour once a week."),
        ],
    },
    {
        "title": "How to start freelancing?",
        "description": "Web dev skills, no client yet. Where to begin without getting scammed?",
        "author": "SideHustleDev",
        "bubble_title": "Job Seekers Network",
        "answers": [
            ("PortfolioDev", "3 solid portfolio projects pehle — real problem solve karo."),
            ("LinkedInPro", "Profile optimize + small posts on learnings."),
            ("ReferralPlease", "Pehle clients network se aate hain usually, cold outreach second."),
            ("RemoteHunt", "Platforms pe low bids se race mat karo initially."),
            ("FreshGrad", "Contract clear likho — scope, payment timeline, revisions."),
            ("CareerSwitch", "Start part-time while employed if possible — less pressure."),
            ("HRInsider", "Red flag: client payment upfront maangna weird contexts mein."),
        ],
    },
    {
        "title": "Good cafés for reading books?",
        "description": "Quiet, good light, won't rush you out if you sit 2 hours with one coffee.",
        "author": "MidnightReader",
        "bubble_title": "Book Readers Club",
        "answers": [
            ("LibraryGhost", "Actual library best hai honestly — free + designed for reading."),
            ("PageTurner", "Cafe mein window seat + morning hours = minimum disturbance."),
            ("KindleFan", "Earplugs carry karo, indie cafes better than chains."),
            ("FictionLover", "Ask staff politely if long sit ok hai — mostly fine weekdays pe."),
            ("PoetryNerd", "Book + cafe combo ke liye soft music wale places choose karo."),
            ("AudiobookGuy", "Park bench season mein underrated option hai."),
        ],
    },
    {
        "title": "Which programming language should I learn first?",
        "description": "Complete beginner, goal is web apps eventually. Confused by too many opinions online.",
        "author": "CareerStarter",
        "bubble_title": "Software Engineers",
        "answers": [
            ("CodeNinja", "Python ya JavaScript — dono beginner friendly, JS agar web clear goal hai."),
            ("BugHunter", "Language se zyada problem solving seekho — syntax baad mein aata hai."),
            ("InterviewPrep", "One language deeply > five superficially."),
            ("StartupCoder", "Build small projects week 2 se — tutorial hell se bacho."),
            ("StackOverflow", "FreeCodeCamp / Odin path structured hai beginners ke liye."),
            ("MemeDev", "JavaScript ecosystem chaotic hai but job market mein useful 😅"),
            ("RemoteDev", "After basics, pick framework based on project not hype."),
            ("NightOwlDev", "Consistency matters most — 30 min daily."),
        ],
    },
    {
        "title": "Recommended weekend trip destinations?",
        "description": "Within 4-5 hours travel, good for small group 4 people, budget moderate.",
        "author": "WeekendPlanner",
        "bubble_title": "Travelers Community",
        "answers": [
            ("WeekendEscape", "Hill station 3hr drive — monsoon mein green, winter mein clear views."),
            ("Backpacker", "Homestay book karo, hotel se zyada local feel."),
            ("SoloTrip", "4 log = car pool economical + flexible stops."),
            ("BudgetTravel", "Off-season weekday trip sasta padta hai."),
            ("MountainLover", "Trek easy grade choose karo agar mixed fitness group hai."),
            ("RoadTrip", "Playlist + snacks + early start = less traffic."),
            ("TravelPhoto", "Sunrise spot research pehle se karo — worth it."),
            ("BeachBum", "Coastal option bhi hai agar mountains recent ho chuke hain."),
            ("LocalGuide", "Local food joints > tourist restaurant always."),
        ],
    },
]
