from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bubbles", "0007_question_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="bubble",
            name="system_seed_content",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Demo/onboarding content generated by seed_demo_content.",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="system_seed_content",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Demo/onboarding message from seed_demo_content.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="system_seed_content",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Demo/onboarding question from seed_demo_content.",
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="system_seed_content",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Demo/onboarding answer from seed_demo_content.",
            ),
        ),
    ]
